port:  4000
markdown: kramdown
name: Codeando Monterrey
url: http://codeandomonterrey.org
title: Codeando Monterrey
description: "Comunidad de Hacking Cívico de Monterrey"
encoding: utf-8
timezone: America/Chicago
gems:
  - jekyll-redirect-from
future: true
